In [9]:
import nltk
nltk.download("all")

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/basque_grammars.zip.
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/biocreative_ppi.zip.
[nltk_data]    | Downloadin

True

In [ ]:
# from nltk.corpus import PlaintextCorpusReader as p
# new_corpus=p('/content/new_corpus','.*')

In [2]:
import pandas as pd
data=pd.read_csv('/content/drive/MyDrive/IMDB Dataset.csv')
data=data.iloc[0:100]
data

review sentiment
0   One of the other reviewers has mentioned that ...  positive
1   A wonderful little production. <br /><br />The...  positive
2   I thought this was a wonderful way to spend ti...  positive
3   Basically there's a family where a little boy ...  negative
4   Petter Mattei's "Love in the Time of Money" is...  positive
..                                                ...       ...
95  Daniel Day-Lewis is the most versatile actor a...  positive
96  My guess would be this was originally going to...  negative
97  Well, I like to watch bad horror B-Movies, cau...  negative
98  This IS the worst movie I have ever seen, as w...  negative
99  I have been a Mario fan for as long as I can r...  positive

[100 rows x 2 columns]

In [3]:
unclean_docs=data['review'].tolist()

In [ ]:
# import re
# cleaned_list=[]
# for i in range(len(unclean_docs)):
#   cleaned_content= re.sub('[^a-zA-Z0-9\.]', ' ', unclean_docs[i])
#   cleaned_content=" ".join(cleaned_content.split())
#   cleaned_list.append(cleaned_content)
# print(cleaned_list)

['One of the other reviewers has mentioned that after watching just 1 Oz episode you ll be hooked. They are right as this is exactly what happened with me. br br The first thing that struck me about Oz was its brutality and unflinching scenes of violence which set in right from the word GO. Trust me this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs sex or violence. Its is hardcore in the classic use of the word. br br It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda. Em City is home to many..Aryans Muslims gangstas Latinos Christians Italians Irish and more....so scuffles death stares dodgy dealings and shady agreements are never far away. br br I would say the main appeal of the show is due to the fact that it goes where other s

In [4]:
import re
def clean_tweets(review):
  cleaned_content = re.sub(r'https?:/\/\S+', '', review)
  cleaned_content = re.sub(r'@[A-Za-z0-9]+', '', cleaned_content)
  cleaned_content= re.sub('[^a-zA-Z0-9\.]', ' ', cleaned_content)
  cleaned_content = re.sub('[0-9]+','', cleaned_content)
  cleaned_content=" ".join(cleaned_content.split())
  cleaned_content=cleaned_content.lower()
  return cleaned_content

data['clean_review'] = data['review'].apply(clean_tweets)

In [5]:
data['review'].iloc[0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

In [6]:
documents=[]
documents=data['clean_review'].tolist()
documents[0]

'one of the other reviewers has mentioned that after watching just oz episode you ll be hooked. they are right as this is exactly what happened with me. br br the first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go. trust me this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs sex or violence. its is hardcore in the classic use of the word. br br it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda. em city is home to many..aryans muslims gangstas latinos christians italians irish and more....so scuffles death stares dodgy dealings and shady agreements are never far away. br br i would say the main appeal of the show is due to the fact that it goes where other show

In [7]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize,sent_tokenize

In [10]:
new_docs=[]
for i in documents:
  tokenizer = nltk.RegexpTokenizer(r"[a-z,A-Z]+")
  new_tokens = tokenizer.tokenize(i)
  new_tokens = [t.lower() for t in new_tokens]
  new_tokens =[t for t in new_tokens if len(t)!=1]
  new_tokens =[t for t in new_tokens if len(t)!=2]
  new_tokens =[t for t in new_tokens if t not in stopwords.words("english")]
  new_review=""
  for j in new_tokens:
    new_review=new_review+' '+j
  new_docs.append(new_review) 
new_docs[0]

' one reviewers mentioned watching episode hooked right exactly happened first thing struck brutality unflinching scenes violence set right word trust show faint hearted timid show pulls punches regards drugs sex violence hardcore classic use word called nickname given oswald maximum security state penitentary focuses mainly emerald city experimental section prison cells glass fronts face inwards privacy high agenda city home many aryans muslims gangstas latinos christians italians irish scuffles death stares dodgy dealings shady agreements never far away would say main appeal show due fact goes shows dare forget pretty pictures painted mainstream audiences forget charm forget romance mess around first episode ever saw struck nasty surreal say ready watched developed taste got accustomed high levels graphic violence violence injustice crooked guards sold nickel inmates kill order get away well mannered middle class inmates turned prison bitches due lack street skills prison experience 

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer
vector_tfidf=TfidfVectorizer()
x=vector_tfidf.fit_transform(new_docs)
print("Shape of the vector is :",x.shape)
print("\nTfidf Vector :\n")
print(x.toarray())

Shape of the vector is : (100, 4518)

Tfidf Vector :

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [12]:
tfidf_dataframe=pd.DataFrame(x.toarray(),columns=vector_tfidf.get_feature_names())
tfidf_dataframe

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


abbot  abbreviated  abetted  abiding  ability      able  abraham  \
0     0.0      0.00000      0.0      0.0      0.0  0.000000      0.0   
1     0.0      0.00000      0.0      0.0      0.0  0.000000      0.0   
2     0.0      0.00000      0.0      0.0      0.0  0.000000      0.0   
3     0.0      0.00000      0.0      0.0      0.0  0.000000      0.0   
4     0.0      0.00000      0.0      0.0      0.0  0.000000      0.0   
..    ...          ...      ...      ...      ...       ...      ...   
95    0.0      0.00000      0.0      0.0      0.0  0.000000      0.0   
96    0.0      0.11814      0.0      0.0      0.0  0.000000      0.0   
97    0.0      0.00000      0.0      0.0      0.0  0.000000      0.0   
98    0.0      0.00000      0.0      0.0      0.0  0.086899      0.0   
99    0.0      0.00000      0.0      0.0      0.0  0.000000      0.0   

    absolute  absolutely  absorb  ...  zack  zany  zellweger  zero     zeus  \
0        0.0         0.0     0.0  ...   0.0   0.0        0.0   0.0  0.00000   
1        0.0         0.0     0.0  ...   0.0   0.0        0.0   0.0  0.00000   
2        0.0         0.0     0.0  ...   0.0   0.0        0.0   0.0  0.00000   
3        0.0         0.0     0.0  ...   0.0   0.0        0.0   0.0  0.00000   
4        0.0         0.0     0.0  ...   0.0   0.0        0.0   0.0  0.00000   
..       ...         ...     ...  ...   ...   ...        ...   ...      ...   
95       0.0         0.0     0.0  ...   0.0   0.0        0.0   0.0  0.00000   
96       0.0         0.0     0.0  ...   0.0   0.0        0.0   0.0  0.23628   
97       0.0         0.0     0.0  ...   0.0   0.0        0.0   0.0  0.00000   
98       0.0         0.0     0.0  ...   0.0   0.0        0.0   0.0  0.00000   
99       0.0         0.0     0.0  ...   0.0   0.0        0.0   0.0  0.00000   

      zombie  zone  zoo  zooms  zwick  
0   0.000000   0.0  0.0    0.0    0.0  
1   0.000000   0.0  0.0    0.0    0.0  
2   0.000000   0.0  0.0    0.0    0.0  
3   0.243178   0.0  0.0    0.0    0.0  
4   0.000000   0.0  0.0    0.0    0.0  
..       ...   ...  ...    ...    ...  
95  0.000000   0.0  0.0    0.0    0.0  
96  0.000000   0.0  0.0    0.0    0.0  
97  0.000000   0.0  0.0    0.0    0.0  
98  0.000000   0.0  0.0    0.0    0.0  
99  0.000000   0.0  0.0    0.0    0.0  

[100 rows x 4518 columns]

In [13]:
column_names=tfidf_dataframe.columns.tolist()
print(column_names)

['abbot', 'abbreviated', 'abetted', 'abiding', 'ability', 'able', 'abraham', 'absolute', 'absolutely', 'absorb', 'abstracted', 'absurd', 'abusive', 'academy', 'accent', 'accented', 'accents', 'accentuate', 'accepted', 'accepting', 'accepts', 'accident', 'accidentally', 'accomplish', 'accomplished', 'accomplishes', 'according', 'account', 'accountant', 'accounts', 'accurate', 'accuses', 'accustomed', 'achieve', 'achieved', 'achievement', 'achingly', 'acolyte', 'acquired', 'across', 'acroyd', 'act', 'acted', 'acting', 'action', 'actions', 'activate', 'actor', 'actors', 'actress', 'actresses', 'acts', 'actual', 'actually', 'ada', 'adams', 'adapted', 'add', 'added', 'addict', 'addiction', 'adding', 'addition', 'address', 'adequate', 'adjuster', 'admitted', 'adrian', 'adult', 'advent', 'adventure', 'advise', 'affair', 'affected', 'affection', 'affects', 'afraid', 'africa', 'aftermath', 'afternoons', 'afterwards', 'age', 'aged', 'ageing', 'agenda', 'agent', 'aggravate', 'aggression', 'aging'

In [14]:
query=input("ENTER SEARCH QUERY : ")
print("Your entered query is : "+query)

ENTER SEARCH QUERY : dark movies with gory scenes and comedy
Your entered query is : dark movies with gory scenes and comedy


In [15]:
query_tfidf=vector_tfidf.transform([query])
print(query_tfidf.toarray())

[[0. 0. 0. ... 0. 0. 0.]]


In [28]:
from sklearn.metrics.pairwise import cosine_similarity
sim1=cosine_similarity(x,query_tfidf)
column_name=[]
column_name.append("similarity")
similarity_dataframe=pd.DataFrame(sim1,columns=column_name,index=new_docs)
# similarity_dataframe.rename(columns = {"0":'similarity'}, inplace = True)
similarity_dataframe

similarity
 one reviewers mentioned watching episode hooke...    0.014947
 wonderful little production filming technique ...    0.057984
 thought wonderful way spend time hot summer we...    0.078453
 basically family little boy jake thinks zombie...    0.000000
 petter mattei love time money visually stunnin...    0.000000
...                                                        ...
 daniel day lewis versatile actor alive english...    0.000000
 guess would originally going least two parts t...    0.000000
 well like watch bad horror movies cause think ...    0.091147
 worst movie ever seen well worst probably ever...    0.012061
 mario fan long remember fond memories playing ...    0.000000

[100 rows x 1 columns]

In [36]:
n=int(input("Enter the number of relavant documents to display"))

Enter the number of relavant documents to display4


In [29]:
similarity_df= similarity_dataframe.sort_values(['similarity'], ascending=[False])
similarity_df

similarity
 besides boring scenes oppressive dark movie tr...    0.139432
 well like watch bad horror movies cause think ...    0.091147
 ever watched movie lost plot well even really ...    0.087041
 thought wonderful way spend time hot summer we...    0.078453
 busty beauty stacie randall plays pvc clad bad...    0.077938
...                                                        ...
 taut organically gripping edward dmytryk cross...    0.000000
 movie frustrating everything seemed energetic ...    0.000000
 karen carpenter story shows little singer kare...    0.000000
 okay series kind takes route week week david m...    0.000000
 mario fan long remember fond memories playing ...    0.000000

[100 rows x 1 columns]

In [31]:
index_df=[]
simi=[]
simi=list(similarity_df.similarity)
index_df=list(similarity_df.index)
print(simi)
print(index_df)

[0.13943163519574622, 0.09114661160111925, 0.0870408316958226, 0.07845331679403947, 0.07793809417052641, 0.06480189123332214, 0.0579835952699449, 0.055419451584039964, 0.05208191904913484, 0.05000305234712385, 0.04918868699077104, 0.04773287839395564, 0.046380842004594386, 0.04452256204182474, 0.04419552705090212, 0.04392505689388447, 0.04343715990424137, 0.04309390779085683, 0.03943622795547269, 0.038995538675366086, 0.032498842871063194, 0.0280303858480499, 0.02687379616059126, 0.025901398746757485, 0.025627713763905574, 0.025103833971058958, 0.022686561789898734, 0.022256800686096583, 0.02224870624770403, 0.021385981137984855, 0.021314412151179046, 0.020369686720647165, 0.02012701752301567, 0.018556837123470737, 0.017497269534158404, 0.017200312326430444, 0.016868018796455803, 0.01651848782823112, 0.014946988859161384, 0.01471452465102994, 0.014201836372821026, 0.013538467934055545, 0.012977921836275804, 0.012190615490699995, 0.01206132555203279, 0.011299816126328112, 0.010168835152

In [37]:
final_dict= dict(zip(index_df,simi))

top_n = list(final_dict.items())[:n]
top_n


[(' besides boring scenes oppressive dark movie tried portray kind moral fell flat message redeeming qualities top think could make librarians look unglamorous',
  0.13943163519574622),
 (' well like watch bad horror movies cause think interesting see stupidity unability creators shoot seriously good movie always compare movies example spielberg works understand huge difference see like wood movies cause inept funny people chilling funny even interesting extremely boring horror movie without anything makes even bad movies watchable acting screenplay direction thrills even blood extremely inept amateurish film definitely worst movie ever seen seen lot worst movies believe warned',
  0.09114661160111925),
 (' ever watched movie lost plot well even really one begin begin achingly tedious scenes heroine sitting around house actually sense menace even foreboding created even apparently constant thunderstorms strangely never actually heard house great double glazing house apparently miles to

In [39]:
sim2=cosine_similarity(x)
doc_sim=pd.DataFrame(sim2)
doc_sim

0         1         2         3         4         5         6   \
0   1.000000  0.028093  0.055569  0.022008  0.023538  0.004958  0.030079   
1   0.028093  1.000000  0.051356  0.028146  0.020288  0.021682  0.014927   
2   0.055569  0.051356  1.000000  0.008758  0.032508  0.019102  0.023865   
3   0.022008  0.028146  0.008758  1.000000  0.016811  0.016471  0.011203   
4   0.023538  0.020288  0.032508  0.016811  1.000000  0.037281  0.021473   
..       ...       ...       ...       ...       ...       ...       ...   
95  0.013313  0.010084  0.035193  0.015404  0.047752  0.068943  0.023224   
96  0.016039  0.029695  0.047335  0.030945  0.036620  0.026120  0.044409   
97  0.006775  0.040370  0.033701  0.042601  0.041041  0.095748  0.042837   
98  0.025591  0.032326  0.016751  0.027173  0.039201  0.055426  0.045025   
99  0.022131  0.007773  0.021421  0.009532  0.028954  0.016182  0.041562   

          7         8         9   ...        90        91        92        93  \
0   0.094715  0.028581  0.000000  ...  0.017723  0.034807  0.029817  0.015746   
1   0.021306  0.047486  0.025109  ...  0.012006  0.026521  0.021683  0.036153   
2   0.044571  0.018752  0.047604  ...  0.037449  0.038126  0.034679  0.026522   
3   0.015969  0.024747  0.029604  ...  0.018023  0.036550  0.012775  0.009954   
4   0.031135  0.071000  0.015111  ...  0.015553  0.045342  0.031021  0.054685   
..       ...       ...       ...  ...       ...       ...       ...       ...   
95  0.016328  0.023299  0.016151  ...  0.023187  0.036908  0.021444  0.032656   
96  0.061536  0.053605  0.025828  ...  0.038142  0.038720  0.024761  0.019155   
97  0.065280  0.075231  0.069788  ...  0.029270  0.084438  0.024554  0.047304   
98  0.049495  0.079156  0.015528  ...  0.021775  0.071720  0.040117  0.019512   
99  0.038238  0.022985  0.009687  ...  0.008803  0.013998  0.036761  0.024398   

          94        95        96        97        98        99  
0   0.022224  0.013313  0.016039  0.006775  0.025591  0.022131  
1   0.019184  0.010084  0.029695  0.040370  0.032326  0.007773  
2   0.007175  0.035193  0.047335  0.033701  0.016751  0.021421  
3   0.021307  0.015404  0.030945  0.042601  0.027173  0.009532  
4   0.010041  0.047752  0.036620  0.041041  0.039201  0.028954  
..       ...       ...       ...       ...       ...       ...  
95  0.012650  1.000000  0.053873  0.042080  0.025778  0.011707  
96  0.019058  0.053873  1.000000  0.089000  0.065706  0.016666  
97  0.029449  0.042080  0.089000  1.000000  0.127286  0.015270  
98  0.044680  0.025778  0.065706  0.127286  1.000000  0.014102  
99  0.010904  0.011707  0.016666  0.015270  0.014102  1.000000  

[100 rows x 100 columns]

In [ ]:
query_token=query.split(" ")
print(query_token)

['movies', 'with', 'flinching', 'and', 'gory', 'scenes', 'and', 'comedy']


In [ ]:
from nltk.probability import FreqDist
query_dist=FreqDist(query_token)
query_dist

FreqDist({'and': 2, 'movies': 1, 'with': 1, 'flinching': 1, 'gory': 1, 'scenes': 1, 'comedy': 1})

In [ ]:
df=[]
tf=[]
keys=[]
for i,j in query_dist.items():
  count=0
  for k in new_docs:
    if i in k:
      count+=1
    else:
      pass
  df.append(count)
  tf.append(j)
  keys.append(i)
  
print(keys)
print(tf)
print(df)

['movies', 'with', 'flinching', 'and', 'gory', 'scenes', 'comedy']
[1, 1, 1, 2, 1, 1, 1]
[29, 13, 1, 52, 1, 19, 8]


In [ ]:
import numpy as np
n=len(tf)
query_tfidf=[]
for i in range(len(tf)):
  query_tfidf.append(tf[i]*np.log(n/(1+df[i])))
query_tfidf  

[-1.455287232606842,
 -0.6931471805599453,
 1.252762968495368,
 -4.048763528993617,
 1.252762968495368,
 -1.0498221244986778,
 -0.25131442828090605]

In [ ]:
query_df=pd.DataFrame(query_tfidf,index=keys)
query_df=(query_df.T)
query_vec=query_df.values
print(query_vec)

[[-1.45528723 -0.69314718  1.25276297 -4.04876353  1.25276297 -1.04982212
  -0.25131443]]


In [ ]:
query_vecs=[]
for i in query_vec:
  for j in i:
    query_vecs.append(j)
print(query_vecs)

[-1.455287232606842, -0.6931471805599453, 1.252762968495368, -4.048763528993617, 1.252762968495368, -1.0498221244986778, -0.25131442828090605]


In [ ]:
print(new_docs)

[' one reviewers mentioned watching episode hooked right exactly happened first thing struck brutality unflinching scenes violence set right word trust show faint hearted timid show pulls punches regards drugs sex violence hardcore classic use word called nickname given oswald maximum security state penitentary focuses mainly emerald city experimental section prison cells glass fronts face inwards privacy high agenda city home many aryans muslims gangstas latinos christians italians irish scuffles death stares dodgy dealings shady agreements never far away would say main appeal show due fact goes shows dare forget pretty pictures painted mainstream audiences forget charm forget romance mess around first episode ever saw struck nasty surreal say ready watched developed taste got accustomed high levels graphic violence violence injustice crooked guards sold nickel inmates kill order get away well mannered middle class inmates turned prison bitches due lack street skills prison experience

In [ ]:
doc_vecs=tfidf_dataframe.values.tolist()
print(doc_vecs[0])

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.08383650542361877, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.07693017428110169, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.08383650542361877, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0769

In [ ]:
# from numpy.linalg import norm
# cosine_sim=[]
# for i in range(len(doc_vecs)):
#   cosine = np.dot(doc_vecs[i],query_tfidf)/(norm(query_tfidf)*norm(doc_vecs[i]))
#   cosine_sim.append(cosine)
# cosine_sim

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_sim=[]
for i in range(len(doc_vecs)):
  vec_list=doc_vecs[i]
  cosine_sim.append(cosine_similarity(query_vecs,vec_list))
cosine_sim

ValueError: ignored

In [ ]:
print(query_vecs)
print(doc_vecs[0])

[-1.455287232606842, -0.6931471805599453, 1.252762968495368, -4.048763528993617, 1.252762968495368, -1.0498221244986778, -0.25131442828090605]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.08383650542361877, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.07693017428110169, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.08383650542361877, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0